export const guidesEs = {
  "hail-damage-roof-inspection-dfw": {
    title: "Como saber si el granizo dano su techo en DFW",
    metaTitle: "Como saber si el granizo dano su techo en DFW | Guia de inspeccion gratis",
    metaDescription: "No esta seguro si el granizo dano su techo en DFW? Aprenda las senales tempranas, que debe revisar una inspeccion y cuando pedir una revision gratis.",
    eyebrow: "Guia util para propietarios",
    intro: "El dano por granizo no siempre se nota desde la calle. Esta guia explica que senales conviene revisar en DFW y cuando tiene sentido pedir una inspeccion profesional.",
    summary: "Una guia sencilla para detectar a tiempo problemas de techo relacionados con granizo y decidir cuando conviene programar una inspeccion.",
    keywords: ["dano por granizo techo DFW", "como saber si el granizo dano el techo", "inspeccion gratis de techo DFW"],
    keyPoints: ["El granizo puede acortar la vida del techo incluso antes de una filtracion.", "Los danos suelen verse primero en tejas, ventilaciones, tapajuntas y canaletas.", "Una inspeccion con fotos ayuda a saber si conviene reparar, reemplazar o solo vigilar."],
    sections: [
      { id: "what-hail-can-do", label: "Que Puede Pasar", title: "Como puede afectar el granizo a un techo", paragraphs: ["El granizo puede golpear tejas, aflojar granulos, agrietar materiales y debilitar zonas que desde abajo todavia parecen normales.", "En DFW tambien es comun ver marcas en ventilaciones, canaletas y piezas metalicas expuestas."], bullets: ["Tejas golpeadas", "Perdida de granulos", "Golpes en canaletas", "Zonas debiles que despues filtran"] },
      { id: "signs-from-ground", label: "Que Revisar", title: "Senales que puede revisar desde el suelo", paragraphs: ["No necesita subirse al techo. Puede revisar canaletas, bajantes, pantallas, bordes del techo y cualquier parte visible desde un angulo seguro.", "Si hubo una tormenta fuerte y ve granulos, golpes o desgaste raro, vale la pena pedir una inspeccion."] },
      { id: "inspection-includes", label: "Que Incluye", title: "Que deberia incluir una buena inspeccion por granizo", paragraphs: ["Una inspeccion util debe incluir fotos, una explicacion clara y orientacion honesta sobre si hace falta actuar ahora o seguir observando.", "La idea no es presionarlo para cambiar el techo, sino ayudarle a entender la condicion real."] },
      { id: "when-to-schedule", label: "Cuando Agendar", title: "Cuando conviene programar una inspeccion", paragraphs: ["Si hubo granizo hace poco, si sus vecinos tambien estan revisando techos o si nota algo raro en la linea del techo, lo mas prudente suele ser revisarlo pronto.", "Detectar dano temprano le da mas tiempo para decidir con calma."] },
    ],
    faq: [
      { question: "Puede haber dano por granizo aunque no exista una filtracion?", answer: "Si. Muchos techos muestran dano antes de que entre agua a la vivienda." },
      { question: "Necesito subirme al techo para revisar?", answer: "No. Lo mas seguro es observar desde el suelo y pedir una inspeccion si algo le preocupa." },
    ],
  },
  "roof-repair-near-me-north-richland-hills": {
    title: "Reparacion de techo cerca de mi en North Richland Hills",
    metaTitle: "Reparacion de techo en North Richland Hills, TX | Inspeccion gratis",
    metaDescription: "Busca reparacion de techo cerca de usted en North Richland Hills? Conozca las senales importantes, los problemas mas comunes y cuando conviene pedir una inspeccion gratis.",
    eyebrow: "Guia local de techos",
    intro: "Cuando un propietario busca reparacion de techo cerca de mi, casi siempre ya hay una fuga, dano por tormenta o una preocupacion urgente. Esta guia explica que revisar, por que actuar temprano importa y como una inspeccion clara ayuda a tomar una mejor decision.",
    summary: "Una guia local y facil de entender sobre fugas, dano por tormenta y reparaciones de techo en North Richland Hills.",
    keywords: ["reparacion de techo North Richland Hills", "fuga de techo North Richland Hills", "reparacion urgente de techo North Richland Hills", "contratista de techos North Richland Hills TX"],
    keyPoints: [
      "Una fuga o una teja suelta suele costar mas si se deja pasar tiempo.",
      "Una buena reparacion empieza por encontrar la causa, no solo tapar el sintoma.",
      "Una inspeccion local ayuda a decidir si conviene reparar, vigilar o pensar en reemplazo.",
    ],
    sections: [
      { id: "why-local-repair-searches-matter", label: "Por Que Importa", title: "Por que los propietarios buscan reparacion de techo cerca de mi", paragraphs: ["La mayoria de las personas no hace esa busqueda hasta que algo ya preocupa: una mancha en el techo interior, una teja faltante o un cambio visible despues del mal clima.", "Ese tipo de busqueda suele significar que el siguiente paso debe ser practico: entender que esta pasando, que tan urgente es y si hace falta reparar ahora o inspeccionar primero."] },
      { id: "common-roof-problems", label: "Problemas Comunes", title: "Problemas de techo que suelen requerir reparacion en North Richland Hills", paragraphs: ["Las fugas, las tejas levantadas o faltantes, el dano en tapajuntas y el desgaste por tormenta son algunas de las razones mas comunes por las que un propietario busca ayuda local.", "En North Richland Hills y otras zonas de DFW, el granizo y el viento pueden dejar danos que al principio parecen pequenos, pero luego se vuelven mucho mas caros."], bullets: ["Fugas y manchas de agua", "Tejas sueltas o faltantes", "Tapajuntas danados", "Dano por granizo o tormenta"] },
      { id: "why-early-repair-helps", label: "Actuar A Tiempo", title: "Por que un problema pequeno puede crecer rapido", paragraphs: ["Un detalle pequeno en el techo no siempre se queda pequeno. Una teja floja, una grieta o un punto debil puede terminar en dano interior, moho y un arreglo mucho mas amplio despues de la siguiente lluvia.", "Por eso conviene revisar el estado del techo temprano, antes de que el problema ya sea una filtracion seria o un gasto grande."] },
      { id: "repair-approach", label: "Enfoque De Reparacion", title: "Como un mejor proceso de reparacion protege la casa por mas tiempo", paragraphs: ["Una buena reparacion comienza revisando la condicion general del techo, no solo el sintoma visible. Eso incluye tejas, tapajuntas, bordes, drenaje y zonas donde el agua podria estar entrando.", "Asi el propietario entiende mejor que ocasiono el problema, si basta con reparar y que ayuda a reducir que vuelva a pasar lo mismo."] },
      { id: "storm-damage-and-next-steps", label: "Siguiente Paso", title: "Cuando el dano por tormenta y el seguro entran en la conversacion", paragraphs: ["Algunas reparaciones se deben al desgaste normal y otras aparecen justo despues de granizo, lluvia fuerte o viento. Cuando podria haber dano por tormenta, las fotos y notas claras ayudan mucho.", "Incluso si al final solo hace falta reparar y no reemplazar, una inspeccion local hace que el siguiente paso sea mucho mas claro y menos estresante."] },
    ],
    faq: [
      { question: "Toda fuga en North Richland Hills significa reemplazar el techo?", answer: "No. Algunas fugas vienen de dano localizado o tapajuntas desgastados, mientras que otras si apuntan a un problema mayor. Una inspeccion ayuda a diferenciarlo." },
      { question: "Vale la pena revisar el techo aunque la fuga parezca pequena?", answer: "Si. Una fuga pequena puede esconder un problema mayor, especialmente despues de una tormenta." },
    ],
  },
  "roof-storm-damage-insurance-texas": {
    title: "Como suele funcionar un reclamo de seguro por dano de techo en Texas",
    metaTitle: "Guia de seguro por dano de techo en Texas | Que debe esperar un propietario",
    metaDescription: "Aprenda como suelen funcionar los reclamos de seguro por dano de techo en Texas, que conviene documentar y como ayuda una inspeccion clara.",
    eyebrow: "Guia util para propietarios",
    intro: "Si una tormenta golpeo su techo y no sabe que hacer despues, esta guia explica el proceso con palabras sencillas para que pueda decidir con menos estres.",
    summary: "Una guia en lenguaje claro sobre documentacion, inspeccion y lo que suelen encontrar los propietarios de Texas despues de una tormenta fuerte.",
    keywords: ["seguro dano techo Texas", "reclamo seguro techo tormenta Texas", "inspeccion techo seguro DFW"],
    keyPoints: ["El primer paso suele ser documentar lo ocurrido y revisar si hay dano visible.", "Una buena inspeccion ayuda a entender mejor la conversacion antes de hablar con el ajustador.", "Fotos claras y notas sencillas reducen confusion en el siguiente paso."],
    sections: [
      { id: "first-steps", label: "Primer Paso", title: "Que hacer primero despues de una tormenta", paragraphs: ["Primero asegurese de que la vivienda este bien y revise desde el suelo cualquier cambio visible.", "Si no hay una emergencia, lo mas util suele ser una inspeccion que documente claramente el dano visible antes de entrar en la conversacion del seguro."] },
      { id: "what-to-document", label: "Que Documentar", title: "Que conviene guardar como registro", paragraphs: ["No necesita un sistema complicado. Unas cuantas fotos claras, la fecha de la tormenta y notas sobre lo que cambio ya ayudan bastante.", "Si hay inspeccion, las fotos del techo, tapajuntas y canaletas facilitan mucho la siguiente conversacion."], bullets: ["Fecha de la tormenta", "Dano visible afuera", "Cambios o filtraciones interiores", "Fotos de la inspeccion"] },
      { id: "adjuster-process", label: "Revision Del Seguro", title: "Como suele verse la visita del ajustador", paragraphs: ["Cada caso es distinto, pero normalmente el ajustador revisa el dano reportado, inspecciona la propiedad y compara lo visible con la informacion del reclamo.", "Lo mas util es llegar a esa conversacion con una idea clara de lo que realmente se encontro en el techo."] },
      { id: "where-inspection-helps", label: "Como Ayuda", title: "Por que una inspeccion clara sigue siendo importante", paragraphs: ["Algunos techos necesitan reparacion, otros reemplazo y otros solo vigilancia. Una inspeccion ayuda a diferenciar eso antes de tomar decisiones apresuradas.", "Tambien ayuda a quienes solo quieren orientacion honesta despues de la tormenta."] },
    ],
    faq: [
      { question: "Conviene hablar con el seguro antes de la inspeccion?", answer: "Muchas personas se sienten mas seguras cuando primero entienden el estado visible del techo." },
      { question: "Todo dano por tormenta implica un reclamo?", answer: "No siempre. Algunos techos requieren accion inmediata y otros solo seguimiento o reparaciones menores." },
    ],
  },
  "signs-of-wind-damage-on-your-roof": {
    title: "Senales de dano por viento en su techo despues de una tormenta en North Texas",
    metaTitle: "Senales de dano por viento en su techo | Guia para propietarios de North Texas",
    metaDescription: "Aprenda las senales mas comunes de dano por viento en un techo, que deben revisar los propietarios de North Texas y cuando conviene pedir una inspeccion.",
    eyebrow: "Guia util para propietarios",
    intro: "El dano por viento no siempre se ve grave al principio. Esta guia explica las senales mas comunes despues de una tormenta en North Texas y cuando conviene revisar el techo.",
    summary: "Una guia practica para detectar a tiempo problemas de techo causados por viento y decidir cuando pedir una inspeccion local.",
    keywords: ["senales dano por viento techo", "dano por viento techo North Texas", "inspeccion techo despues de viento"],
    keyPoints: ["El viento suele aflojar tejas y bordes antes de que aparezca una filtracion.", "El dano puede verse como tejas levantadas, faltantes o zonas expuestas.", "Una inspeccion rapida despues de una tormenta fuerte puede evitar un problema mas costoso."],
    sections: [
      { id: "common-signs", label: "Senales Comunes", title: "Las senales mas comunes de dano por viento", paragraphs: ["Despues de una tormenta fuerte, el dano por viento suele verse como tejas levantadas, tapajuntas doblados, piezas faltantes o zonas expuestas.", "A veces tambien aparecen restos acumulados o lineas del techo que ya no se ven parejas."], bullets: ["Tejas levantadas", "Piezas faltantes", "Tapajuntas doblados", "Bordes desparejos"] },
      { id: "subtle-warning-signs", label: "Senales Sutiles", title: "Cambios pequenos que muchos propietarios no notan", paragraphs: ["No siempre se nota a primera vista. A veces la primera senal es granulo en canaletas o una pequena mancha interior.", "Si esas senales aparecen despues de mucho viento, suele valer la pena revisar antes de la siguiente tormenta."] },
      { id: "when-it-is-urgent", label: "Cuando Es Urgente", title: "Cuando conviene tomarlo como algo mas urgente", paragraphs: ["Si ya entra agua, faltan tejas o hay zonas expuestas visibles desde el suelo, lo mejor es actuar rapido.", "Aunque no haya filtracion, cambios visibles en bordes o remates tambien justifican una inspeccion oportuna."] },
      { id: "what-inspection-checks", label: "Que Revisa", title: "Que suele revisar una inspeccion por dano de viento", paragraphs: ["La inspeccion suele revisar la superficie, bordes, tapajuntas, penetraciones y zonas con riesgo de filtracion.", "Tambien debe explicar de forma simple si hace falta actuar ya."] },
    ],
    faq: [
      { question: "Puede el dano por viento causar filtraciones despues aunque hoy no haya agua?", answer: "Si. Tejas levantadas o bordes flojos pueden pasar desapercibidos al principio y luego dejar entrar agua." },
      { question: "El dano por viento es distinto al dano por granizo?", answer: "Si. El granizo suele golpear materiales, mientras el viento los levanta, afloja o arranca." },
    ],
  },
  "what-roof-adjusters-look-for-during-an-insurance-inspection": {
    title: "Que revisa un ajustador de techo durante una inspeccion del seguro",
    metaTitle: "Que revisa un ajustador de techo | Guia para propietarios en Texas",
    metaDescription: "Aprenda que suele revisar un ajustador de techo durante una inspeccion del seguro, que deben documentar los propietarios en Texas y como prepararse antes de la visita.",
    eyebrow: "Guia util para propietarios",
    intro: "Si una tormenta dano su techo y pronto tendra una inspeccion del seguro, ayuda mucho saber que es lo que el ajustador realmente va a revisar. Esta guia explica que suele observar, que conviene documentar y como llegar a la visita con menos confusion.",
    summary: "Una guia clara sobre lo que suele inspeccionar un ajustador de techo, como se documenta el dano por tormenta y como puede prepararse un propietario en Texas.",
    keywords: [
      "que revisa un ajustador de techo",
      "inspeccion de ajustador de techo seguro",
      "que busca el ajustador en un techo",
      "inspeccion de techo seguro Texas",
    ],
    keyPoints: [
      "Los ajustadores suelen enfocarse en dano visible y documentable relacionado con tormenta.",
      "Normalmente comparan danos por granizo o viento con desgaste, envejecimiento y problemas previos del techo.",
      "Fotos claras y una revision previa ayudan al propietario a entender mejor la conversacion.",
    ],
    sections: [
      { id: "inspection-scope", label: "Alcance", title: "Que intenta confirmar normalmente un ajustador", paragraphs: ["Un ajustador de seguro normalmente no llega para dar consejos generales de mantenimiento. Su objetivo principal suele ser revisar condiciones visibles, documentar el dano y decidir si la perdida reportada parece estar relacionada con un evento cubierto como granizo o viento.", "Eso significa que la inspeccion suele centrarse en lo que puede verse, fotografiarse, medirse y relacionarse con la tormenta reportada. Mientras mas clara este la condicion del techo, mas sencilla suele ser la conversacion."] },
      { id: "damage-signs", label: "Senales De Dano", title: "Las condiciones del techo que los ajustadores suelen revisar", paragraphs: ["Los ajustadores suelen revisar marcas de impacto de granizo, moretones en tejas, tejas levantadas o dobladas, piezas faltantes, dano en tapajuntas, base expuesta y otras senales visibles de que el techo podria haber perdido parte de su capacidad para desviar el agua.", "Tambien suelen observar componentes relacionados como ventilaciones, caballetes, canaletas, bajantes y piezas metalicas blandas porque esas zonas a veces muestran el impacto de la tormenta con mas claridad que las tejas principales."], bullets: ["Impactos o moretones por granizo", "Tejas levantadas o dobladas por viento", "Piezas faltantes o zonas expuestas", "Golpes en tapajuntas, ventilaciones o canaletas", "Puntos visibles con riesgo de filtracion"] },
      { id: "coverage-questions", label: "Cobertura", title: "Por que el ajustador compara dano por tormenta con desgaste o envejecimiento", paragraphs: ["Una de las preguntas mas importantes durante la inspeccion es si la condicion del techo parece estar relacionada con una tormenta cubierta o con envejecimiento, desgaste prolongado, reparaciones anteriores o problemas de instalacion.", "Por eso a veces aparecen expresiones como dano cosmetico, dano funcional, desgaste normal o condiciones preexistentes. Aunque el techo tenga problemas reales, la revision sigue enfocandose en que tipo de dano hay y cual parece ser su causa."] },
      { id: "preparation", label: "Preparacion", title: "Que puede hacer el propietario antes de la inspeccion del seguro", paragraphs: ["No necesita convertirse en experto en techos antes de la visita, pero si ayuda reunir algunos datos basicos. Anote la fecha de la tormenta, tome fotos desde el suelo de cualquier dano visible, escriba si hubo cambios interiores por humedad y guarde fotos de inspecciones o reparaciones anteriores si las tiene.", "Si ya se hizo una inspeccion de techo, tener fotos claras y notas sencillas hace la conversacion mucho mas facil porque usted ya entiende lo que podria estar en el techo antes de que llegue el ajustador."], bullets: ["Fecha de la tormenta", "Fotos del dano visible afuera", "Notas sobre filtraciones o manchas nuevas", "Registros de reparaciones anteriores si existen", "Fotos de inspeccion si un techador ya reviso el techo"] },
      { id: "inspection-day", label: "Dia De La Visita", title: "Que suele pasar durante la visita del ajustador", paragraphs: ["Muchos propietarios imaginan una reunion larga y muy tecnica, pero la visita suele ser mas directa. El ajustador puede revisar la superficie del techo, observar dano exterior relacionado, ver evidencia interior si hace falta, tomar fotos y documentar lo que encuentra.", "En Texas suele ser util que el propietario este presente si puede, para responder preguntas basicas, explicar que cambios noto despues de la tormenta y asegurarse de que se mencionen todas las preocupaciones visibles."] },
      { id: "next-steps", label: "Siguiente Paso", title: "Que hacer despues de que termine la inspeccion", paragraphs: ["Despues de la visita, lo normal es revisar con calma el estimado, el alcance o la decision del reclamo. Si algo no esta claro, conviene pedir una explicacion escrita de lo que se observo y de lo que si o no fue incluido.", "Incluso si el resultado del seguro aun no es definitivo, contar con un resumen claro del estado del techo ayuda a decidir si el siguiente paso es reparar, pensar en reemplazo o simplemente seguir observando."] },
    ],
    faq: [
      { question: "Conviene hacer una inspeccion de techo antes de que llegue el ajustador?", answer: "Muchos propietarios lo prefieren porque asi entienden mejor la condicion visible del techo antes de hablar del seguro." },
      { question: "El ajustador solo revisa las tejas?", answer: "No. Tambien suele revisar tapajuntas, ventilaciones, caballetes, canaletas y otros componentes del techo que pueden mostrar dano por tormenta." },
      { question: "Si hay dano visible, eso significa que el seguro lo cubrira?", answer: "No siempre. La inspeccion tambien suele considerar la causa del dano, la cobertura de la poliza y si el problema parece venir de la tormenta o del desgaste." },
      { question: "Es util estar en casa durante la inspeccion?", answer: "Si, cuando sea posible. El propietario puede explicar cuando empezo el dano, donde aparecieron filtraciones y que cambio despues de la tormenta." },
    ],
  },
  "how-long-does-a-roof-inspection-take-in-dfw": {
    title: "Cuanto tarda normalmente una inspeccion de techo en DFW",
    metaTitle: "Cuanto tarda una inspeccion de techo en DFW | Guia de inspeccion gratis",
    metaDescription: "Aprenda cuanto suele tardar una inspeccion de techo en DFW, que factores cambian el tiempo y que puede esperar antes, durante y despues de la visita.",
    eyebrow: "Guia util para propietarios",
    intro: "Una de las preguntas mas comunes antes de agendar es cuanto tiempo tomara realmente una inspeccion de techo. Esta guia explica que suele afectar la duracion, que incluye normalmente la visita y que puede esperar un propietario en DFW de principio a fin.",
    summary: "Una guia clara sobre cuanto suelen tardar las inspecciones de techo en DFW y que puede esperar un propietario durante el proceso.",
    keywords: [
      "cuanto tarda una inspeccion de techo",
      "tiempo de inspeccion de techo",
      "cuanto tarda una inspeccion de techo en DFW",
      "inspeccion gratis de techo DFW",
    ],
    keyPoints: [
      "Muchas inspecciones residenciales duran menos de una hora, pero el tiempo depende del tamano y estado del techo.",
      "El dano por tormenta, el acceso dificil y la documentacion pueden alargar la visita.",
      "Una buena inspeccion debe incluir hallazgos claros, fotos y pasos siguientes faciles de entender.",
    ],
    sections: [
      { id: "typical-time", label: "Tiempo Habitual", title: "Cuanto suele durar una inspeccion de techo", paragraphs: ["En muchas casas, una inspeccion residencial basica puede completarse en unos 30 a 60 minutos. Aun asi, el tiempo exacto depende del tamano del techo, de lo complejo que sea el diseno y de si hay dano por tormenta o preocupaciones de filtracion que requieran una revision mas detallada.", "Un techo pequeno y sencillo puede revisarse mas rapido, mientras que una casa mas grande con varias secciones, pendientes marcadas o senales visibles de dano por tormenta puede llevar mas tiempo."] },
      { id: "what-affects-timing", label: "Que Cambia El Tiempo", title: "Que puede hacer que una inspeccion tarde mas", paragraphs: ["No todas las inspecciones son iguales. Si el techo tiene varios niveles, zonas empinadas, dano en tapajuntas, tejas faltantes o senales de granizo o viento, la inspeccion puede llevar mas tiempo porque hay mas areas que revisar con cuidado.", "La visita tambien puede tardar mas si se necesita documentacion fotografica para hablar con el seguro o si el propietario tiene preguntas concretas sobre filtraciones, reparaciones o si conviene pensar en reemplazo."], bullets: ["Techos mas grandes o complejos", "Dano visible por granizo o viento", "Revision por filtracion o humedad interior", "Documentacion fotografica detallada", "Preguntas sobre reparar o reemplazar"] },
      { id: "during-visit", label: "Durante La Visita", title: "Que suele ocurrir durante la inspeccion", paragraphs: ["La inspeccion suele incluir la revision de la superficie del techo, los bordes, los tapajuntas, las penetraciones, las cumbreras y las zonas visibles donde podria haber problemas de drenaje o riesgo de filtracion.", "En muchos casos tambien hay una breve conversacion con el propietario sobre lo que cambio despues de una tormenta, si han aparecido filtraciones y que fue lo que motivo la cita."] },
      { id: "after-inspection", label: "Despues De La Inspeccion", title: "Que deberia pasar cuando la inspeccion termina", paragraphs: ["Una inspeccion util no termina cuando la persona baja del techo. El propietario deberia quedarse con una explicacion clara de lo que se encontro, si hay algo urgente y cual deberia ser el siguiente paso.", "Normalmente eso significa hallazgos sencillos de entender, fotos de apoyo y orientacion practica sobre si el techo necesita reparacion, plan de reemplazo, seguimiento relacionado con seguro o simplemente observacion."] },
      { id: "when-faster-or-longer", label: "Rapida O Mas Larga", title: "Cuando una inspeccion es mas corta y cuando toma mas tiempo", paragraphs: ["Si el techo es bastante estandar, facil de acceder y no muestra senales obvias de dano por tormenta, la inspeccion puede avanzar con rapidez. Si el techo es mas grande, mas inclinado, mas antiguo o muestra varias zonas preocupantes, suele necesitarse mas tiempo para revisarlo bien.", "Y eso generalmente es positivo. Una inspeccion cuidadosa que tarda un poco mas suele ser mucho mas util que una visita apresurada que deja pasar detalles importantes."] },
      { id: "booking-expectations", label: "Antes De Agendar", title: "Que conviene esperar antes de programar la visita", paragraphs: ["La mayoria de los propietarios no necesita preparar mucho antes de la cita, pero ayuda saber cuando fue la tormenta, si aparecieron filtraciones interiores y si hay zonas especificas de preocupacion alrededor de la casa.", "Si la razon de la inspeccion esta relacionada con tormenta, tener esos datos listos puede hacer que la visita sea mas eficiente y que la siguiente conversacion sea mucho mas clara."] },
    ],
    faq: [
      { question: "Puede una inspeccion de techo durar menos de 30 minutos?", answer: "Algunos techos pequenos y sencillos pueden revisarse rapido, pero muchas inspecciones duran mas cerca de 30 a 60 minutos segun el techo y las preocupaciones a revisar." },
      { question: "El dano por tormenta hace que la inspeccion dure mas?", answer: "Si. El granizo, el viento y las filtraciones suelen requerir una revision mas detallada y mas fotos." },
      { question: "Conviene que el propietario este presente durante la inspeccion?", answer: "Suele ayudar. Estar disponible hace mas facil explicar cuando fue la tormenta, si hubo filtraciones y que preocupa del techo." },
      { question: "Que deberia recibir despues de la inspeccion?", answer: "Una explicacion clara de lo encontrado, los siguientes pasos y documentacion fotografica cuando sea necesaria." },
    ],
  },
} as const;
