export const guidesEs = {
  "hail-damage-roof-inspection-dfw": {
    title: "Como saber si el granizo dano su techo en DFW",
    metaTitle: "Como saber si el granizo dano su techo en DFW | Guia de inspeccion gratis",
    metaDescription: "No esta seguro si el granizo dano su techo en DFW? Aprenda las senales tempranas, que debe revisar una inspeccion y cuando pedir una revision gratis.",
    eyebrow: "Guia util para propietarios",
    intro: "El dano por granizo no siempre se nota desde la calle. Esta guia explica que senales conviene revisar en DFW y cuando tiene sentido pedir una inspeccion profesional.",
    summary: "Una guia sencilla para detectar a tiempo problemas de techo relacionados con granizo y decidir cuando conviene programar una inspeccion.",
    keywords: ["dano por granizo techo DFW", "como saber si el granizo dano el techo", "inspeccion gratis de techo DFW"],
    keyPoints: ["El granizo puede acortar la vida del techo incluso antes de una filtracion.", "Los danos suelen verse primero en tejas, ventilaciones, tapajuntas y canaletas.", "Una inspeccion con fotos ayuda a saber si conviene reparar, reemplazar o solo vigilar."],
    sections: [
      { id: "what-hail-can-do", label: "Que Puede Pasar", title: "Como puede afectar el granizo a un techo", paragraphs: ["El granizo puede golpear tejas, aflojar granulos, agrietar materiales y debilitar zonas que desde abajo todavia parecen normales.", "En DFW tambien es comun ver marcas en ventilaciones, canaletas y piezas metalicas expuestas."], bullets: ["Tejas golpeadas", "Perdida de granulos", "Golpes en canaletas", "Zonas debiles que despues filtran"] },
      { id: "signs-from-ground", label: "Que Revisar", title: "Senales que puede revisar desde el suelo", paragraphs: ["No necesita subirse al techo. Puede revisar canaletas, bajantes, pantallas, bordes del techo y cualquier parte visible desde un angulo seguro.", "Si hubo una tormenta fuerte y ve granulos, golpes o desgaste raro, vale la pena pedir una inspeccion."] },
      { id: "inspection-includes", label: "Que Incluye", title: "Que deberia incluir una buena inspeccion por granizo", paragraphs: ["Una inspeccion util debe incluir fotos, una explicacion clara y orientacion honesta sobre si hace falta actuar ahora o seguir observando.", "La idea no es presionarlo para cambiar el techo, sino ayudarle a entender la condicion real."] },
      { id: "when-to-schedule", label: "Cuando Agendar", title: "Cuando conviene programar una inspeccion", paragraphs: ["Si hubo granizo hace poco, si sus vecinos tambien estan revisando techos o si nota algo raro en la linea del techo, lo mas prudente suele ser revisarlo pronto.", "Detectar dano temprano le da mas tiempo para decidir con calma."] },
    ],
    faq: [
      { question: "Puede haber dano por granizo aunque no exista una filtracion?", answer: "Si. Muchos techos muestran dano antes de que entre agua a la vivienda." },
      { question: "Necesito subirme al techo para revisar?", answer: "No. Lo mas seguro es observar desde el suelo y pedir una inspeccion si algo le preocupa." },
    ],
  },
  "roof-repair-near-me-north-richland-hills": {
    title: "Reparacion de techo cerca de mi en North Richland Hills",
    metaTitle: "Reparacion de techo en North Richland Hills, TX | Inspeccion gratis",
    metaDescription: "Busca reparacion de techo cerca de usted en North Richland Hills? Conozca las senales importantes, los problemas mas comunes y cuando conviene pedir una inspeccion gratis.",
    eyebrow: "Guia local de techos",
    intro: "Cuando un propietario busca reparacion de techo cerca de mi, casi siempre ya hay una fuga, dano por tormenta o una preocupacion urgente. Esta guia explica que revisar, por que actuar temprano importa y como una inspeccion clara ayuda a tomar una mejor decision.",
    summary: "Una guia local y facil de entender sobre fugas, dano por tormenta y reparaciones de techo en North Richland Hills.",
    keywords: ["reparacion de techo North Richland Hills", "fuga de techo North Richland Hills", "reparacion urgente de techo North Richland Hills", "contratista de techos North Richland Hills TX"],
    keyPoints: [
      "Una fuga o una teja suelta suele costar mas si se deja pasar tiempo.",
      "Una buena reparacion empieza por encontrar la causa, no solo tapar el sintoma.",
      "Una inspeccion local ayuda a decidir si conviene reparar, vigilar o pensar en reemplazo.",
    ],
    sections: [
      { id: "why-local-repair-searches-matter", label: "Por Que Importa", title: "Por que los propietarios buscan reparacion de techo cerca de mi", paragraphs: ["La mayoria de las personas no hace esa busqueda hasta que algo ya preocupa: una mancha en el techo interior, una teja faltante o un cambio visible despues del mal clima.", "Ese tipo de busqueda suele significar que el siguiente paso debe ser practico: entender que esta pasando, que tan urgente es y si hace falta reparar ahora o inspeccionar primero."] },
      { id: "common-roof-problems", label: "Problemas Comunes", title: "Problemas de techo que suelen requerir reparacion en North Richland Hills", paragraphs: ["Las fugas, las tejas levantadas o faltantes, el dano en tapajuntas y el desgaste por tormenta son algunas de las razones mas comunes por las que un propietario busca ayuda local.", "En North Richland Hills y otras zonas de DFW, el granizo y el viento pueden dejar danos que al principio parecen pequenos, pero luego se vuelven mucho mas caros."], bullets: ["Fugas y manchas de agua", "Tejas sueltas o faltantes", "Tapajuntas danados", "Dano por granizo o tormenta"] },
      { id: "why-early-repair-helps", label: "Actuar A Tiempo", title: "Por que un problema pequeno puede crecer rapido", paragraphs: ["Un detalle pequeno en el techo no siempre se queda pequeno. Una teja floja, una grieta o un punto debil puede terminar en dano interior, moho y un arreglo mucho mas amplio despues de la siguiente lluvia.", "Por eso conviene revisar el estado del techo temprano, antes de que el problema ya sea una filtracion seria o un gasto grande."] },
      { id: "repair-approach", label: "Enfoque De Reparacion", title: "Como un mejor proceso de reparacion protege la casa por mas tiempo", paragraphs: ["Una buena reparacion comienza revisando la condicion general del techo, no solo el sintoma visible. Eso incluye tejas, tapajuntas, bordes, drenaje y zonas donde el agua podria estar entrando.", "Asi el propietario entiende mejor que ocasiono el problema, si basta con reparar y que ayuda a reducir que vuelva a pasar lo mismo."] },
      { id: "storm-damage-and-next-steps", label: "Siguiente Paso", title: "Cuando el dano por tormenta y el seguro entran en la conversacion", paragraphs: ["Algunas reparaciones se deben al desgaste normal y otras aparecen justo despues de granizo, lluvia fuerte o viento. Cuando podria haber dano por tormenta, las fotos y notas claras ayudan mucho.", "Incluso si al final solo hace falta reparar y no reemplazar, una inspeccion local hace que el siguiente paso sea mucho mas claro y menos estresante."] },
    ],
    faq: [
      { question: "Toda fuga en North Richland Hills significa reemplazar el techo?", answer: "No. Algunas fugas vienen de dano localizado o tapajuntas desgastados, mientras que otras si apuntan a un problema mayor. Una inspeccion ayuda a diferenciarlo." },
      { question: "Vale la pena revisar el techo aunque la fuga parezca pequena?", answer: "Si. Una fuga pequena puede esconder un problema mayor, especialmente despues de una tormenta." },
    ],
  },
  "roof-storm-damage-insurance-texas": {
    title: "Como suele funcionar un reclamo de seguro por dano de techo en Texas",
    metaTitle: "Guia de seguro por dano de techo en Texas | Que debe esperar un propietario",
    metaDescription: "Aprenda como suelen funcionar los reclamos de seguro por dano de techo en Texas, que conviene documentar y como ayuda una inspeccion clara.",
    eyebrow: "Guia util para propietarios",
    intro: "Si una tormenta golpeo su techo y no sabe que hacer despues, esta guia explica el proceso con palabras sencillas para que pueda decidir con menos estres.",
    summary: "Una guia en lenguaje claro sobre documentacion, inspeccion y lo que suelen encontrar los propietarios de Texas despues de una tormenta fuerte.",
    keywords: ["seguro dano techo Texas", "reclamo seguro techo tormenta Texas", "inspeccion techo seguro DFW"],
    keyPoints: ["El primer paso suele ser documentar lo ocurrido y revisar si hay dano visible.", "Una buena inspeccion ayuda a entender mejor la conversacion antes de hablar con el ajustador.", "Fotos claras y notas sencillas reducen confusion en el siguiente paso."],
    sections: [
      { id: "first-steps", label: "Primer Paso", title: "Que hacer primero despues de una tormenta", paragraphs: ["Primero asegurese de que la vivienda este bien y revise desde el suelo cualquier cambio visible.", "Si no hay una emergencia, lo mas util suele ser una inspeccion que documente claramente el dano visible antes de entrar en la conversacion del seguro."] },
      { id: "what-to-document", label: "Que Documentar", title: "Que conviene guardar como registro", paragraphs: ["No necesita un sistema complicado. Unas cuantas fotos claras, la fecha de la tormenta y notas sobre lo que cambio ya ayudan bastante.", "Si hay inspeccion, las fotos del techo, tapajuntas y canaletas facilitan mucho la siguiente conversacion."], bullets: ["Fecha de la tormenta", "Dano visible afuera", "Cambios o filtraciones interiores", "Fotos de la inspeccion"] },
      { id: "adjuster-process", label: "Revision Del Seguro", title: "Como suele verse la visita del ajustador", paragraphs: ["Cada caso es distinto, pero normalmente el ajustador revisa el dano reportado, inspecciona la propiedad y compara lo visible con la informacion del reclamo.", "Lo mas util es llegar a esa conversacion con una idea clara de lo que realmente se encontro en el techo."] },
      { id: "where-inspection-helps", label: "Como Ayuda", title: "Por que una inspeccion clara sigue siendo importante", paragraphs: ["Algunos techos necesitan reparacion, otros reemplazo y otros solo vigilancia. Una inspeccion ayuda a diferenciar eso antes de tomar decisiones apresuradas.", "Tambien ayuda a quienes solo quieren orientacion honesta despues de la tormenta."] },
    ],
    faq: [
      { question: "Conviene hablar con el seguro antes de la inspeccion?", answer: "Muchas personas se sienten mas seguras cuando primero entienden el estado visible del techo." },
      { question: "Todo dano por tormenta implica un reclamo?", answer: "No siempre. Algunos techos requieren accion inmediata y otros solo seguimiento o reparaciones menores." },
    ],
  },
  "signs-of-wind-damage-on-your-roof": {
    title: "Senales de dano por viento en su techo despues de una tormenta en North Texas",
    metaTitle: "Senales de dano por viento en su techo | Guia para propietarios de North Texas",
    metaDescription: "Aprenda las senales mas comunes de dano por viento en un techo, que deben revisar los propietarios de North Texas y cuando conviene pedir una inspeccion.",
    eyebrow: "Guia util para propietarios",
    intro: "El dano por viento no siempre se ve grave al principio. Esta guia explica las senales mas comunes despues de una tormenta en North Texas y cuando conviene revisar el techo.",
    summary: "Una guia practica para detectar a tiempo problemas de techo causados por viento y decidir cuando pedir una inspeccion local.",
    keywords: ["senales dano por viento techo", "dano por viento techo North Texas", "inspeccion techo despues de viento"],
    keyPoints: ["El viento suele aflojar tejas y bordes antes de que aparezca una filtracion.", "El dano puede verse como tejas levantadas, faltantes o zonas expuestas.", "Una inspeccion rapida despues de una tormenta fuerte puede evitar un problema mas costoso."],
    sections: [
      { id: "common-signs", label: "Senales Comunes", title: "Las senales mas comunes de dano por viento", paragraphs: ["Despues de una tormenta fuerte, el dano por viento suele verse como tejas levantadas, tapajuntas doblados, piezas faltantes o zonas expuestas.", "A veces tambien aparecen restos acumulados o lineas del techo que ya no se ven parejas."], bullets: ["Tejas levantadas", "Piezas faltantes", "Tapajuntas doblados", "Bordes desparejos"] },
      { id: "subtle-warning-signs", label: "Senales Sutiles", title: "Cambios pequenos que muchos propietarios no notan", paragraphs: ["No siempre se nota a primera vista. A veces la primera senal es granulo en canaletas o una pequena mancha interior.", "Si esas senales aparecen despues de mucho viento, suele valer la pena revisar antes de la siguiente tormenta."] },
      { id: "when-it-is-urgent", label: "Cuando Es Urgente", title: "Cuando conviene tomarlo como algo mas urgente", paragraphs: ["Si ya entra agua, faltan tejas o hay zonas expuestas visibles desde el suelo, lo mejor es actuar rapido.", "Aunque no haya filtracion, cambios visibles en bordes o remates tambien justifican una inspeccion oportuna."] },
      { id: "what-inspection-checks", label: "Que Revisa", title: "Que suele revisar una inspeccion por dano de viento", paragraphs: ["La inspeccion suele revisar la superficie, bordes, tapajuntas, penetraciones y zonas con riesgo de filtracion.", "Tambien debe explicar de forma simple si hace falta actuar ya."] },
    ],
    faq: [
      { question: "Puede el dano por viento causar filtraciones despues aunque hoy no haya agua?", answer: "Si. Tejas levantadas o bordes flojos pueden pasar desapercibidos al principio y luego dejar entrar agua." },
      { question: "El dano por viento es distinto al dano por granizo?", answer: "Si. El granizo suele golpear materiales, mientras el viento los levanta, afloja o arranca." },
    ],
  },
} as const;
